return {
    { Nick = "Dziki Kutas", Vocation = "MS", HPMP = 56628 },
    { Nick = "Dwarf", Vocation = "", HPMP = 66121 },
    { Nick = "Avaxis", Vocation = "ED", HPMP = 143520 },
    { Nick = "Czarci pomiot", Vocation = "", HPMP = 120322 },
    { Nick = "Darek Komisariat", Vocation = "ED", HPMP = 118060 },
    { Nick = "Gniot", Vocation = "ED", HPMP = 200144 },
    { Nick = "IzzzzI", Vocation = "MS", HPMP = 205534 },
    { Nick = "Jagermaister", Vocation = "RP", HPMP = 23112 },
    { Nick = "Jestem Karma", Vocation = "", HPMP = 107722 },
    { Nick = "Mrydziu", Vocation = "ED", HPMP = 62732 },
    { Nick = "Mydziu", Vocation = "MS", HPMP = 85440 },
    { Nick = "Natka", Vocation = "MS", HPMP = 89028 },
    { Nick = "Neuker", Vocation = "ED", HPMP = 159426 },
    { Nick = "Silny Mag", Vocation = "MS", HPMP = 75538 },
    { Nick = "Snejker", Vocation = "MS", HPMP = 68832 },
    { Nick = "Sie Jaraa", Vocation = "MS", HPMP = 61136 },
    { Nick = "Techno", Vocation = "ED", HPMP = 178412 },
    { Nick = "TUZZA", Vocation = "MS", HPMP = 102110 },
    { Nick = "Slaby Mag", Vocation = "MS", HPMP = 135640 },    
    { Nick = "Crayzol", Vocation = "MS", HPMP = 89028 },
    { Nick = "Crayzoll", Vocation = "ED", HPMP = 159426 },
    { Nick = "Crayzol MS", Vocation = "MS", HPMP = 75538 },
    { Nick = "Tupac", Vocation = "MS", HPMP = 68832 },
    { Nick = "Zwykly Pet", Vocation = "MS", HPMP = 61136 },
    { Nick = "Raver Man", Vocation = "ED", HPMP = 178412 },
    { Nick = "Harrypotter", Vocation = "MS", HPMP = 102110 },
    { Nick = "Salvatoree", Vocation = "MS", HPMP = 135640 },  
    { Nick = "Fang", Vocation = "MS", HPMP = 61136 },
    { Nick = "Medove", Vocation = "ED", HPMP = 178412 },
    { Nick = "Medove RP", Vocation = "MS", HPMP = 102110 },
    { Nick = "Medove ED", Vocation = "MS", HPMP = 135640 }, 
    { Nick = "Agnieszka", Vocation = "ED", HPMP = 190738 },
    { Nick = "Axel Legenda", Vocation = "ED", HPMP = 261354 },
    { Nick = "Axel Podsypka", Vocation = "RP", HPMP = 123379 },
    { Nick = "Bambiq", Vocation = "MS", HPMP = 210450 },
    { Nick = "Belweder", Vocation = "ED", HPMP = 201978 },
    { Nick = "Boguskaa", Vocation = "ED", HPMP = 275502 },
    { Nick = "BOOM BOX", Vocation = "MS", HPMP = 254216 },
    { Nick = "CHOLERA", Vocation = "RP", HPMP = 190735 },
    { Nick = "Ciri", Vocation = "ED", HPMP = 246958 },
    { Nick = "Corones", Vocation = "RP", HPMP = 105493 },
    { Nick = "Criimson", Vocation = "ED", HPMP = 352328 },
    { Nick = "Damcioo", Vocation = "ED", HPMP = 350138 },
    { Nick = "Dawca Organow", Vocation = "MS", HPMP = 202252 },
    { Nick = "Dawca Orgazmow", Vocation = "EK", HPMP = 173892 },
    { Nick = "Death Bolt", Vocation = "RP", HPMP = 252190 },
    { Nick = "dejS", Vocation = "EK", HPMP = 398400 },
    { Nick = "Dudek", Vocation = "MS", HPMP = 292768 },
    { Nick = "Dyziek Ms", Vocation = "MS", HPMP = 231000 },
    { Nick = "EBOLA", Vocation = "MS", HPMP = 363000 },
    { Nick = "Elite Melon", Vocation = "EK", HPMP = 208945 },
    { Nick = "Elvin", Vocation = "RP", HPMP = 129444 },
    { Nick = "Fec Vito", Vocation = "RP", HPMP = 12357 },
    { Nick = "Grankee", Vocation = "RP", HPMP = 199102 },
    { Nick = "Grimmjow", Vocation = "RP", HPMP = 170470 },
    { Nick = "Grzmocik", Vocation = "MS", HPMP = 224878 },
    { Nick = "Gurosh", Vocation = "RP", HPMP = 245037 },
    { Nick = "Gustafsson", Vocation = "MS", HPMP = 244116 },
    { Nick = "GxC", Vocation = "EK", HPMP = 255537 },
    { Nick = "Hakai", Vocation = "MS", HPMP = 239396 },
    { Nick = "HardeN", Vocation = "ED", HPMP = 298826 },
    { Nick = "Harfa", Vocation = "ED", HPMP = 238418 },
    { Nick = "Ijskoud", Vocation = "RP", HPMP = 146005 },
    { Nick = "Imagram", Vocation = "RP", HPMP = 245020 },
    { Nick = "Kairon", Vocation = "RP", HPMP = 263619 },
    { Nick = "Kajakiem do Afryki", Vocation = "ED", HPMP = 346866 },
    { Nick = "Kamrat", Vocation = "MS", HPMP = 261258 },
    { Nick = "Kastrathor", Vocation = "EK", HPMP = 148850 },
    { Nick = "Keafer Energy", Vocation = "RP", HPMP = 146167 },
    { Nick = "KEEP IT REAL", Vocation = "ED", HPMP = 552164 },
    { Nick = "Kileeroo", Vocation = "MS", HPMP = 350212 },
    { Nick = "Lars Rheiner", Vocation = "ED", HPMP = 252588 },
    { Nick = "Lukas Rp", Vocation = "RP", HPMP = 243820 },
    { Nick = "Lunaria", Vocation = "RP", HPMP = 342565 },
    { Nick = "Magmaar", Vocation = "RP", HPMP = 160194 },
    { Nick = "Mariczka", Vocation = "MS", HPMP = 243134 },
    { Nick = "Marika", Vocation = "ED", HPMP = 210112 },
    { Nick = "Mascote", Vocation = "ED", HPMP = 274976 },
    { Nick = "Mascott", Vocation = "RP", HPMP = 224454 },
    { Nick = "Mefistoteles", Vocation = "RP", HPMP = 138303 },
    { Nick = "Minimajk", Vocation = "MS", HPMP = 267484 },
    { Nick = "Mlody Vuriat", Vocation = "ED", HPMP = 186384 },
    { Nick = "Nakamura", Vocation = "MS", HPMP = 204776 },
    { Nick = "Opresor", Vocation = "RP", HPMP = 191166 },
    { Nick = "Orochimaru", Vocation = "EK", HPMP = 222463 },
    { Nick = "Pasternik", Vocation = "ED", HPMP = 259194 },
    { Nick = "peanut", Vocation = "RP", HPMP = 245140 },
    { Nick = "Pijany Sensei", Vocation = "RP", HPMP = 245304 },
    { Nick = "Pijany Wojak", Vocation = "EK", HPMP = 277929 },
    { Nick = "Pizza Hawajska", Vocation = "RP", HPMP = 159197 },
    { Nick = "Pryszcz na Dupie", Vocation = "RP", HPMP = 149540 },
    { Nick = "Pszczelarz", Vocation = "MS", HPMP = 340108 },
    { Nick = "Return", Vocation = "MS", HPMP = 237808 },
    { Nick = "Shadow Fiend", Vocation = "ED", HPMP = 276674 },
    { Nick = "Shaqqy", Vocation = "MS", HPMP = 187576 },
    { Nick = "SHARA BULLET", Vocation = "MS", HPMP = 229880 },
    { Nick = "Siguardsson", Vocation = "EK", HPMP = 228453 },
    { Nick = "Sisek", Vocation = "RP", HPMP = 148765 },
    { Nick = "Siwucha", Vocation = "RP", HPMP = 147293 },
    { Nick = "Siwyyy", Vocation = "MS", HPMP = 198844 },
    { Nick = "Solo", Vocation = "MS", HPMP = 350232 },
    { Nick = "sznyta", Vocation = "ED", HPMP = 240058 },
    { Nick = "Szybka", Vocation = "ED", HPMP = 286048 },
    { Nick = "Szybkiczubekk", Vocation = "RP", HPMP = 244826 },
    { Nick = "Tamlin", Vocation = "RP", HPMP = 142674 },
    { Nick = "THORP", Vocation = "RP", HPMP = 111773 },
    { Nick = "Tilius", Vocation = "EK", HPMP = 143509 },
    { Nick = "TROUBLE", Vocation = "MS", HPMP = 232138 },
    { Nick = "Tyron", Vocation = "MS", HPMP = 366050 },
    { Nick = "Venox", Vocation = "EK", HPMP = 266083 },
    { Nick = "Vuriat", Vocation = "MS", HPMP = 220064 },
    { Nick = "Waskuu", Vocation = "EK", HPMP = 285883 },
    { Nick = "Wujek Andrut", Vocation = "ED", HPMP = 256844 },
    { Nick = "XAWITO", Vocation = "RP", HPMP = 245095 },
    { Nick = "ZboQ", Vocation = "MS", HPMP = 290764 },
    { Nick = "Zrobie Ci Waleriana", Vocation = "RP", HPMP = 166183 },
    { Nick = "Krizued", Vocation = "ED", HPMP = 78426 },
    { Nick = "Shund", Vocation = "MS", HPMP = 91920 },
    { Nick = "Clever", Vocation = "EK", HPMP = 59794 },
    { Nick = "Venomvinea", Vocation = "ED", HPMP = 116402 },
    { Nick = "Byczek Gls", Vocation = "MS", HPMP = 69388 },
    { Nick = "Chalt", Vocation = "", HPMP = 33225 },
    { Nick = "Debelantos", Vocation = "RP", HPMP = 32836 },
    { Nick = "Dioxs", Vocation = "MS", HPMP = 94214 },
    { Nick = "Edzio Sio", Vocation = "ED", HPMP = 71140 },
    { Nick = "Karola", Vocation = "MS", HPMP = 55614 },
    { Nick = "Kopper", Vocation = "MS", HPMP = 62614 },
    { Nick = "Sebi", Vocation = "EK", HPMP = 65155 },
    { Nick = "SprinterekMs", Vocation = "MS", HPMP = 174078 },
    { Nick = "Timex", Vocation = "RP", HPMP = 55960 },
    { Nick = "Krizurp", Vocation = "RP", HPMP = 44498 },
    { Nick = "Bachor", Vocation = "MS", HPMP = 610 },
    { Nick = "DarkArrow", Vocation = "RP", HPMP = 46161 },
    { Nick = "Jaruszkotem", Vocation = "", HPMP = 0 },
    { Nick = "Krizuek", Vocation = "", HPMP = 0 },
}
