return {
    { Nick = "Dziki Kutas", Vocation = "MS", HPMP = 56628 },
    { Nick = "Dwarf", Vocation = "", HPMP = 66121 },
    { Nick = "Avaxis", Vocation = "ED", HPMP = 143520 },
    { Nick = "Czarci pomiot", Vocation = "", HPMP = 120322 },
    { Nick = "Darek Komisariat", Vocation = "ED", HPMP = 118060 },
    { Nick = "Gniot", Vocation = "ED", HPMP = 200144 },
    { Nick = "IzzzzI", Vocation = "MS", HPMP = 205534 },
    { Nick = "Jagermaister", Vocation = "RP", HPMP = 23112 },
    { Nick = "Jestem Karma", Vocation = "", HPMP = 107722 },
    { Nick = "Mrydziu", Vocation = "ED", HPMP = 62732 },
    { Nick = "Mydziu", Vocation = "MS", HPMP = 85440 },
    { Nick = "Natka", Vocation = "MS", HPMP = 89028 },
    { Nick = "Neuker", Vocation = "ED", HPMP = 159426 },
    { Nick = "Silny Mag", Vocation = "MS", HPMP = 75538 },
    { Nick = "Snejker", Vocation = "MS", HPMP = 68832 },
    { Nick = "Sie Jaraa", Vocation = "MS", HPMP = 61136 },
    { Nick = "Techno", Vocation = "ED", HPMP = 178412 },
    { Nick = "TUZZA", Vocation = "MS", HPMP = 102110 },
}
